version: '3'
services:
  dsm:
    container_name: dsm
    restart: unless-stopped
    image: vdsm/virtual-dsm:latest
    environment:
      DISK_SIZE: "4000G"
      GPU: "Y"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
      - /dev/dri
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    volumes:
      - /root/workspace/data/dsm/storage:/storage
    stop_grace_period: 2m
